dist: trusty
languaje: bash
before_deploy:
- git config --local user.name "IkerST"
- git config --local user.email "ikersanditrejo@gmail.com"
- git tag "RedWolf-twrp-$(date +"%d%m%Y")"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get -qq install g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo apt-get install -y axel xz-utils bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk figlet libc6-i386 gcc-arm-none-eabi
  - sudo apt-get install python-virtualenv
jdk:
- openjdk8
script:
  - virtualenv virtualenv
  - source virtualenv/bin/activate
  - bash build.sh
