languaje: bash
before_deploy:
- git config --local user.name "IkerST"
- git config --local user.email "ikersanditrejo@gmail.com"
- git tag "RedWolf-twrp-$(date +"%d%m%Y")"
before_install:
- sudo apt-get update
- sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib
  git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool
  libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop
  pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev figlet
script:
- bash build.sh
